import { type Prisma } from "@prisma/client";

export const legendaryItems: Prisma.ItemCreateInput[] = [
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "a magician's key",
        description: "An obsidian skeleton key that creates a private plane.",
        damage: null,
        activationCost: 5,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "ancient ranger's pouch",
        description:
            "A pouch filled with seeds that grow into sentient tree creatures.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "bane",
        description: "A magical dagger that tries to charm nearby creatures.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "blood pact",
        description:
            "A sentient blade that curses whoever picks it up to feel an unquenchable bloodthirst.",
        damage: 4,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "cloak of a hundred billion stars",
        description:
            "A magic cloak that allows an Invoker to commune with the stars.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "conway's comrades",
        description: "A set of magic toy figurines that can come alive to do battle.",
        damage: null,
        activationCost: 4,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "cosmic purse",
        description: "A magic bag that can hold an unlimited number of items.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "creighton's fascinators",
        description: "A pair of tall black boots that cast an aura of leadership.",
        damage: null,
        activationCost: 5,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "echo",
        description: "A ring that duplicates spells and reflects them.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "fable",
        description:
            "A weapon handed down through generations that records the deeds of its wielder.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "guile",
        description: "A cameo brooch that can create an illusory visage.",
        damage: null,
        activationCost: 1,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "gungrox's coin",
        description: "A smooth platinum coin that randomize a player's role.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "harmony",
        description:
            "A weathered wooden lute that seeks music through the omniverse.",
        damage: null,
        activationCost: 5,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "harper's haven",
        description: "A small stone figurine with world-shaking power.",
        damage: null,
        activationCost: 10,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "june's blanket",
        description: "A patchwork blanket that offers love and comfort.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "lorelai's wand",
        description: "A magic wand that imbues the wielder with incredible power.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "loren's luminous starglass",
        description: "A magic telescope that carries its wielder through the stars.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "multivious map",
        description:
            "A sentient map of the stars that loves to pontificate about possibility.",
        damage: null,
        activationCost: 1,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "nightmare",
        description: "A greatsword that gives walking nightmares.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "prismatic circlet",
        description: "This crystal crown that projects a major illusion.",
        damage: null,
        activationCost: 3,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "resplendent plate",
        description:
            "An indomitable breastplate that makes the wearer resistant to attacks.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "rebellion",
        description:
            "An ancient bronze shield that lights the fires of independence.",
        damage: null,
        activationCost: 4,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "shadow",
        description:
            "A magic shortblade forged by a malevolent god that reaps souls.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "the cosmic cruiser",
        description:
            "A magic starship that can travel through space and the omniverse.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "the toll",
        description: "An iridescent coin that offers eternal paradise.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "unity",
        description: "A magic pin allowing the wearer to comprehend languages.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "legendary",
        rollTheDie: false,
        title: "vol",
        description: "A magic spear that can become a bolt of lightning.",
        damage: 3,
        activationCost: null,
    },
];
