import type { CharacterProfile } from "@/types/form";

export const defaultSheet: CharacterProfile = {
    name: "",
    pronoun: "",
    age: null,
    height: null,
    appearance: {
        body: "",
        face: "",
        vibe: "",
        clothing: "",
        movement: "",
    },
    home: {
        short_description: "",
        peculiarity: "",
    },
    belief: "",
    flaw: "",
    dream: "",
    roleId: null,
};

export const bodyOptions = [
    "scales",
    "worn scars",
    "iridescent skin",
    "rack of muscles",
    "towering physique",
    "speckled complexion",
    "barrel-sized belly",
    "head of tentacles",
    "generous curves",
    "elongated limbs",
    "bumpy exterior",
    "willowy frame",
    "sculpted hair",
    "stout stature",
    "lived-in body",
    "vestigial tail",
    "webbed fins",
    "rough hide",
];

export const faceOptions = [
    "gaunt face",
    "sharp teeth",
    "fulsome cheeks",
    "large, pointy ears",
    "vestigial antennae",
    "knee-length beard",
    "devastating smile",
    "windswept face",
    "manicured fuzz",
    "ridged forehead",
    "triangular head",
    "timeworn face",
    "romantic eyes",
    "severe jawline",
    "skeptical eyes",
    "radiant smile",
    "burning eyes",
];

export const vibeOptions = [
    "long shadow",
    "sleepy mood",
    "sparkling gaze",
    "eternal grimace",
    "bursting energy",
    "an air of mystery",
    "gentle disposition",
    "androgynous vibes",
    "thousand-yard stare",
    "tightly wound energy",
    "brooding presence",
    "friendly demeanor",
    "meandering gaze",
    "graceful posture",
    "captivating grin",
    "raucous laugh",
    "flawless poise",
    "fiery temper",
];

export const clothingOptions = [
    "etched leather armor",
    "a billowing jumpsuit",
    "a tightly fitted tunic",
    "religious vestments",
    "nicked chainmail",
    "runes in my hair",
    "a fluttering cape",
    "weathered rags",
    "a layered dress",
    "a warm cloak",
    "an owl pin",
    "a charmed necklace",
    "a ragged headcover",
    "antique eyeglasses",
    "a patterned hijab",
    "a silken eyepatch",
    "fingerless gloves",
    "a quilted jacket",
    "encrusted cuffs",
    "a feathered cap",
    "a boned bodice",
    "a fancy hat",
];

export const movementOptions = [
    "no sense of urgency",
    "an effortless glide",
    "frenzied footwork",
    "a confident step",
    "great difficulty",
    "a reliable pace",
    "wide-swinging arms",
    "a spring in my step",
    "a singular purpose",
    "no sense of space",
    "music in my feet",
    "an uneven gait",
    "a joyful whistle",
    "relentless focus",
    "casual swagger",
    "apprehension",
    "a heavy step",
    "fearlessness",
];

export const homeShortDescriptionOptions = [
    "a great metropolis",
    "a remote village",
    "a frontier town",
    "a lonely island",
    "a capital city",
    "a seastead",
    "a remote stronghold",
    "a traveling caravan",
    "a hidden warren",
    "a working farm",
    "a roadside inn",
    "a ship at sea",
    "a place I can't name",
    "a subterranean city",
    "a forgotten nation",
    "a mountain town",
    "a city in the mist",
    "a homestead",
];

export const homePeculiarityOptions = [
    "their steady pursuit of pleasure",
    "their easygoing temperament",
    "their unhurried sense of time",
    "treating strangers with love",
    "restoring justice to the land",
    "once ruling a vast empire",
    "creating a world wonder",
    "enduring a great tragedy",
    "their neutral rationality",
    "their warm hospitality",
    "a culture of secrecy",
    "non-hierarchical relationships",
    "plainly stating their intentions",
    "their sense of duty to each other",
    "resisting a brutal ruling order",
    "creating historic works of art",
    "strict adherence to the law",
    "their commercial success",
    "setting cultural trends",
    "their traditional ways",
    "inventing the future",
    "losing a great war",
];

export const beliefOptions = [
    "order",
    "justice",
    "heroism",
    "compassion",
    "generosity",
    "pleasure",
    "pragmatism",
    "honor",
    "power",
    "salvation",
    "the ends",
];

export const flawOptions = [
    "fearful",
    "megalomaniac",
    "foolish",
    "impish",
    "oblivious",
    "thief",
    "hedonist",
    "liar",
    "reckless",
    "wrathful",
    "vain",
];

export const dreamOptions = [
    "returning to my hometown as a renowned hero",
    "freeing myself from a gang that wants me dead",
    "getting revenge on someone who wronged me",
    "finding a corner of the world to make my own",
    "publishing a book that's found in every home",
    "sparking an idea that transforms the world",
    "becoming the greatest scholar in my field",
    "recovering a stolen artifact for my people",
    "stealing from the rich to give to the poor",
    "having my name spoken by my leader",
    "meeting my parents for the first time",
    "spreading my ideal across the land",
    "overturning a corrupt government",
    "producing a timeless work of art",
    "becoming tremendously wealthy",
    "finding the source of eternal life",
    "becoming a leader of my nation",
    "becoming a notorious gambler",
    "making every stranger smile",
    "becoming a master artisan",
    "dying an honorable death",
    "mapping the entire world",
    "meeting the grim reaper",
    "pulling off the big score",
    "traveling to the stars",
    "becoming a celebrity",
    "meeting my god(s)",
    "killing my past",
];
