import { type Prisma } from "@prisma/client";

export const rareItems: Prisma.ItemCreateInput[] = [
    {
        rarity: "rare",
        rollTheDie: false,
        title: "abdellahi's scepter",
        description: "A magic scepter that casts a chilling spell.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "abyssal brand",
        description: "An edged weapon forged by a conniving demon.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "accursed band",
        description: "A translucent magic bracelet that can detect spirits.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "big belt of strong strength",
        description: "An unusually large belt that makes you feel unusually strong.",
        damage: null,
        activationCost: 1,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "bonebreaker",
        description:
            "A giant hammer imbued with magic force that accelerates the weapon as it is swung.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "chaos pearls",
        description: "A bag of luminescent magic pearls that can explode with force.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "dawnbringer",
        description: "A greathammer imbued with radiant light.",
        damage: 2,
        activationCost: 2,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "death adder",
        description: "A small magic tally counter that senses nearby deaths.",
        damage: null,
        activationCost: 1,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "defiance",
        description:
            "A silvered short blade that grants the wielder immunity against mind magic.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "draconis",
        description: "A longsword forged in the flame of a dragon's breath.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "dress of many pockets",
        description:
            "A magic dress that deceptively appears to have no pockets. It has many.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "gideon's shroud",
        description: "A cloak that makes the wearer undetectable by magic.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "lichblade",
        description: "The weapon of a banished lich that casts a malevolent aura.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "masterwork",
        description:
            "A weapon of incredible quality that still bears its maker's mark.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "needful gift box",
        description: "A small wooden box that can produce an object of value.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "perspicacious pot",
        description: "A magic pot that can create a recipe.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "portal chalk",
        description: "A stick of chalk that can open a portal.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "professor prim's mind exploder",
        description: "A magic consumable that bestows a new ability.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "scintillating wand",
        description: "A magic wand that fills the wielder with mischievous thoughts.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "scrying sphere",
        description:
            "A magic crystal ball that gives the user a glimpse at the future.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "scion",
        description: "A magic pincushion that can detect family relations.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "serpentine staff",
        description: "A snakewood staff that can transform into a viper.",
        damage: 2,
        activationCost: 1,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "spell scroll",
        description: "A magic scroll enchanted with a spell.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "spirit trap",
        description: "A crystal orb that attracts and traps spirit creatures nearby.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "the bouncer",
        description: "A magic buckler that turns the table on attackers.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "the compensator",
        description: "A broadsword with an envy problem.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "the eager edge",
        description: "A sentient magic sword that loves to be used.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "rare",
        rollTheDie: false,
        title: "the miracle sponge",
        description: "A sponge with almost no limit to its thirst.",
        damage: null,
        activationCost: null,
    },
];
