import { type Prisma } from "@prisma/client";

export const uncommonItems: Prisma.ItemCreateInput[] = [
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "albatross pendant",
        description:
            "A magic communication device that delivers headlines from the Albatross Press.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "archive",
        description:
            "A talking crystal ball that is programmed to recall information stored inside.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "atlas incognito",
        description:
            "A book of 10 magic stamps that reveals interesting local information.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "blink blade",
        description: "A magic sword that can teleport back to its user's hand.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "brell's boat in a box",
        description: "A small wooden box that can expand into a real, working sloop.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "brell's charismatic couture",
        description:
            "A line of magical shapeshifting garments that automatically find a perfect fit for their wearer.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "brell's limitless ledger",
        description:
            "A magical networked codex that duplicates entries from linked journals.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "brell's tent in a tin",
        description: "A magic tin canister that can deploy a large tent.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: true,
        title: "dim grimoire",
        description:
            "A magic notebook that's risky to read, but can provide great benefits.",
        damage: null,
        activationCost: 4,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "discretion",
        description: "A magic scabbard that can make weapons appear invisible.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "field monitor",
        description:
            "A magic map that can respond to questions and provide useful information.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "friend flute",
        description: "A magic whistle that knows who your friends are.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "glitter bomb",
        description: "A pouch of magic glitter that dispels invisibility.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "goat simulator",
        description:
            "A magic stuff toy goat that can turn into a lifesized illusory goat.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "healing potion",
        description: "A potion that heals you. What were you expecting?",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "kiln gauze",
        description:
            "A container of magic gauze that can be used to repair broken metal weapons.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "light trap",
        description: "A magic glass orb that can be used like a camera.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "lying lyre",
        description:
            "A magic lyre that guides its user's hands to produce a beautiful song.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: true,
        title: "magic potion",
        description:
            "A vial filled with magic liquid that has unpredictable effects.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "mischievous marbles",
        description: "A bag of marbles that seeks out creatures to trip.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "not a pipe",
        description: "This is a pipe. When smoked, it creates a thick magical fog.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "permanent solution",
        description:
            "A small dropper filled with magic liquid that can permanently bond two things together.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "portable potent potable probe",
        description:
            "A small box with a magic dish that can be used to detect poison.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "quiplasher",
        description: "A sentient magic whip that loves witty one-liners.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "ramification",
        description: "A magic battering ram that can shatter wooden doors.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "registrar",
        description:
            "A magic book that automatically senses and records the most commonly-used name of a creature that passes nearby.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "repeater",
        description: "A compact magic crossbow.",
        damage: 4,
        activationCost: 2,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "silvery horn",
        description: "An enchanted horn that can send messages far and wide.",
        damage: null,
        activationCost: 2,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "skycaller amulets",
        description:
            "Pairs of magic amulets that allow their owners to communicate with each other.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the catcher",
        description:
            "A heavy metal gauntlet that allows the wearer to prevent weapon attacks.",
        damage: null,
        activationCost: 1,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the howdy doodat",
        description: "A magic candle that detects illusions.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the lagniappe",
        description: "A weapon with a little extra damage.",
        damage: 3,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the left-handed smoke shifter",
        description: "A metal rod that sends the bearer on an impossible quest.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the sure shot",
        description: "A magic bow that guides its user's hand.",
        damage: 2,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "tricky ticket",
        description: "Magic tickets that can transform into forgeries.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: true,
        title: "untamed magic broom",
        description: "A flying broom with its own agenda.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "the true witness",
        description: "A set of linked magic glasses that share perspectives.",
        damage: null,
        activationCost: null,
    },
    {
        rarity: "uncommon",
        rollTheDie: false,
        title: "wraithfire bomb",
        description: "A dark crystal orb that goes boom.",
        damage: 4,
        activationCost: null,
    },
];
